const questions = [
{ id:1, question:'What is the capital of France?', options:['Berlin','Madrid','Paris','Rome'], correct:2 },
{ id:2, question:'Which planet is known as the Red Planet?', options:['Venus','Mars','Jupiter','Mercury'], correct:1 },
{ id:3, question:'What is the chemical symbol for water?', options:['O2','H2O','CO2','HO'], correct:1 },
{ id:4, question:'Who wrote "Romeo and Juliet"?', options:['Charles Dickens','William Shakespeare','Mark Twain','Leo Tolstoy'], correct:1 },
{ id:5, question:'Which language is primarily spoken in Brazil?', options:['Spanish','Portuguese','English','French'], correct:1 },
{ id:6, question:'How many continents are there?', options:['5','6','7','8'], correct:2 },
{ id:7, question:'What is 9 × 9?', options:['72','81','99','90'], correct:1 },
{ id:8, question:'What does CPU stand for in computers?', options:['Central Processing Unit','Computer Primary Unit','Central Print Unit','Control Processing Unit'], correct:0 },
{ id:9, question:'Which ocean is the largest?', options:['Atlantic','Indian','Pacific','Arctic'], correct:2 },
{ id:10, question:'Who painted the Mona Lisa?', options:['Van Gogh','Pablo Picasso','Leonardo da Vinci','Claude Monet'], correct:2 },
{ id:11, question:'Which gas do plants absorb from the atmosphere?', options:['Oxygen','Nitrogen','Carbon Dioxide','Hydrogen'], correct:2 },
{ id:12, question:'Which country invented paper?', options:['China','Egypt','Greece','India'], correct:0 },
{ id:13, question:'What is the largest land animal?', options:['Elephant','Giraffe','Hippo','Rhino'], correct:0 },
{ id:14, question:'Which instrument has keys, pedals and strings?', options:['Guitar','Violin','Piano','Flute'], correct:2 },
{ id:15, question:'Which element has the symbol Fe?', options:['Fluorine','Iron','Francium','Fermium'], correct:1 },
{ id:16, question:'How many degrees in a right angle?', options:['45','90','180','60'], correct:1 },
{ id:17, question:'What is the capital of Japan?', options:['Seoul','Tokyo','Beijing','Bangkok'], correct:1 },
{ id:18, question:'Which organ pumps blood around the body?', options:['Liver','Lungs','Heart','Kidneys'], correct:2 },
{ id:19, question:'What is the boiling point of water at sea level (°C)?', options:['90','95','100','110'], correct:2 },
{ id:20, question:'Which is the smallest prime number?', options:['0','1','2','3'], correct:2 },
{ id:21, question:'Which year did the first man land on the Moon?', options:['1965','1969','1972','1959'], correct:1 },
{ id:22, question:'Which is the longest river in the world?', options:['Nile','Amazon','Yangtze','Mississippi'], correct:0 },
{ id:23, question:'What currency is used in the UK?', options:['Euro','Dollar','Pound Sterling','Franc'], correct:2 },
{ id:24, question:'Which vitamin is produced when skin exposed to sunlight?', options:['Vitamin A','Vitamin B12','Vitamin C','Vitamin D'], correct:3 },
{ id:25, question:'Which animal is known as the King of the Jungle?', options:['Lion','Tiger','Elephant','Leopard'], correct:0 },
{ id:26, question:'Which metal is liquid at room temperature?', options:['Mercury','Gold','Silver','Copper'], correct:0 },
{ id:27, question:'Who discovered penicillin?', options:['Marie Curie','Alexander Fleming','Isaac Newton','Louis Pasteur'], correct:1 },
{ id:28, question:'Which planet has the most moons?', options:['Mars','Earth','Jupiter','Venus'], correct:2 },
{ id:29, question:'What is the hardest natural substance?', options:['Iron','Diamond','Graphite','Quartz'], correct:1 },
{ id:30, question:'Which city hosted the 2012 Summer Olympics?', options:['Beijing','London','Rio de Janeiro','Tokyo'], correct:1 },
{ id:31, question:'Which language has the most native speakers?', options:['English','Spanish','Mandarin Chinese','Hindi'], correct:2 },
{ id:32, question:'What is the primary ingredient in guacamole?', options:['Tomato','Avocado','Onion','Pepper'], correct:1 },
{ id:33, question:'Which organelle is the powerhouse of the cell?', options:['Nucleus','Mitochondria','Ribosome','Golgi apparatus'], correct:1 },
{ id:34, question:'Which country has the largest population?', options:['India','USA','China','Russia'], correct:2 },
{ id:35, question:'Which instrument is used to measure temperature?', options:['Barometer','Thermometer','Hygrometer','Anemometer'], correct:1 },
{ id:36, question:'Which famous physicist developed the theory of relativity?', options:['Newton','Einstein','Galileo','Bohr'], correct:1 },
{ id:37, question:'Which berry is used to make traditional English jam? (commonly)', options:['Blueberry','Strawberry','Raspberry','Blackberry'], correct:1 },
{ id:38, question:'What language is used to style web pages?', options:['HTML','JavaScript','CSS','Python'], correct:2 },
{ id:39, question:'Which is NOT a JavaScript framework?', options:['React','Angular','Django','Vue'], correct:2 },
{ id:40, question:'Which planet is closest to the Sun?', options:['Earth','Venus','Mercury','Mars'], correct:2 },
{ id:41, question:'Who is the author of "Harry Potter" series?', options:['J.R.R. Tolkien','J.K. Rowling','C.S. Lewis','George R.R. Martin'], correct:1 },
{ id:42, question:'Which metal is commonly used for electrical wiring?', options:['Copper','Aluminum','Titanium','Lead'], correct:0 },
{ id:43, question:'Which organ filters blood and produces urine?', options:['Liver','Heart','Kidney','Lungs'], correct:2 },
{ id:44, question:'Which shape has four equal sides and four right angles?', options:['Rectangle','Rhombus','Square','Parallelogram'], correct:2 },
{ id:45, question:'Which gas is most abundant in the Earth\'s atmosphere?', options:['Oxygen','Nitrogen','Carbon Dioxide','Argon'], correct:1 },
{ id:46, question:'Which country is known for the Great Barrier Reef?', options:['South Africa','Australia','Canada','Brazil'], correct:1 },
{ id:47, question:'Who painted the ceiling of the Sistine Chapel?', options:['Raphael','Michelangelo','Donatello','Caravaggio'], correct:1 },
{ id:48, question:'Which device do we use to look at stars?', options:['Microscope','Binoculars','Telescope','Stethoscope'], correct:2 },
{ id:49, question:'Which is the largest internal organ in the human body?', options:['Liver','Heart','Stomach','Lung'], correct:0 },
{ id:50, question:'Which number comes next in the sequence: 2,4,6,8,...?', options:['9','10','11','12'], correct:1 }
];

export default questions;